### ISSUE TITLE
Nexml.org site still directs to the SourceForge repo, which is stale

### ISSUE THREAD

**Issue by hlapp** [nexml/nexml#6]
Assuming that the Github repo is now the official one for NeXML, the [repo at  SourceForge](https://sourceforge.net/projects/nexml/) should be changed to indicate that the repo has moved (this is part of the settings available to admins).

Also the nexml.org website needs to be fixed to no longer pull in source code displays from the SourceForge repo, because doing so is misleading people.

I am not an admin for the SourceForge site, so I can't fix this myself.

**Comment by rvosa** [comment]
Do you mean there is a specific way to re-direct people to a different repo address or do you mean to just add a note to the project on sf.net? 

I have updated the site generation code to remove the SVN steps as of commit 6a5899b73b455b9ce3fa04475fe5d3e526d25337

**Comment by hlapp** [comment]
On Jan 16, 2014, at 7:25 AM, Rutger Vos wrote:

> Do you mean there is a specific way to re-direct people to a different repo address or do you mean to just add a note to the project on sf.net?
> 
> Go to project home on sf.net, then Admin -> "Update Metadata" -> Click edit icon next to "Project Status" -> check "Moved Project to" and enter Github URL. Hit save.

Example for how this will look like is [PLHDB](https://sourceforge.net/projects/plhdb/).

**Comment by rvosa** [comment]
Done, thanks!

**Comment by rvosa** [comment]
The svn instructions have been removed from the templates. To ensure they don't actually show up any more the site needs to be rebuilt, which I'm going to subsume under #13
