### ISSUE TITLE
Convert nexml.org website to a statically generated site

### ISSUE THREAD

**Issue by hlapp** [nexml/nexml#7]
The [NeXML.org](http://nexml.org) website is currently dependent on a webserver with the capability of dynamically serving content. This is both a liability and (in principle) unnecessary:
1. The site is currently hosted by NESCent, which is unsuitable as a long-term host. More specifically, NESCent main grant support is ending in 12 months, so the need to find an alternative hosting solution isn't theoretical.
2. Of the dynamic functions of the site, any XML validator should be able to validate NeXML documents, and thus a dynamic validator program should not be needed. 
3. The documentation served by the site is in part redundant with the wiki content (the "manual"), and the distinction between these is not clear. Moreover, it should be possible to make documentation generated from the XSD static content.

If the website would only need statically served content, Github pages could be used for this purpose. If not, the server may have to be migrated to SourceForge, leading to two repositories having to remain active.

**Comment by cboettig** [comment]
@rvosa might be able to correct me, but I believe (https://github.com/ropensci/RNeXML/issues/34) the NeXML validator performs a few additional checks beyond XML Schema validation to make sure that id references are also correct.  I don't believe this can be accomplished with a standard XML validator.

**Comment by rvosa** [comment]
Correct.

**Comment by hlapp** [comment]
@rvosa your thoughts then on where to long-term host this service if it is indispensable? And BTW I assume that means that the [TreeBASE NeXML files](https://github.com/rvosa/supertreebase) have then not been run through the validator?

**Comment by rvosa** [comment]
Sorry for the late reply.

The TreeBASE NeXML files are by no means exemplars of proper NeXML, they
are simply a snapshot of the output that TreeBASE produces using the NeXML
Java library. Given the intricacies of the TreeBASE data model (e.g. how
sequences are stored, how taxa are organized) on the one hand, and the
relative liberalism of the Java library on the other, it is inevitable that
there are invalid files.

As for the NeXML web site: a pretty likely location could be in the cloud
here at Naturalis, which is being deployed presently (but not quite
operational, yet).

**Comment by yeban** [comment]
Dynamic aspects of nexml.org is being tracked here: nexml/nexml.github.io#1. Rest is addressed.
